### ISSUE TITLE
Cannot download the TED dataset

### ISSUE THREAD

**Issue by LiuXinqi12** [snap-research/articulated-animation#12]
When I tried to download the Ted dataset, it seemed that all the links failed. I don't know how to fix it. 
In addition, I want to figure out the format of the dataset in the file. I find that the generalization ability of the model is limited for the data collected in the wild, even if I try to use all the pre trained models
Thanks!

/home/liuxinqi/anaconda3/envs/art-ani/lib/python3.7/site-packages/scipy/__init__.py:140: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.15.0)
  UserWarning)
0it [00:00, ?it/s]Can not load video iMFJef3xnmg, broken link
1it [00:27, 27.56s/it]Can not load video Cetg4gu0oQQ, broken link
Can not load video 360bU-vBJOI, broken link
Can not load video xHHb7R3kx40, broken link
Can not load video LnJwH_PZXnM, broken link
5it [00:27,  5.53s/it]Can not load video ClfBxWPkBKU, broken link
Can not load video cK74vhqzeeQ, broken link
Can not load video 1g-1_Y3fvUg, broken link
8it [00:28,  3.59s/it]Can not load video lyR-K2CZIHQ, broken link
9it [00:29,  3.25s/it]Can not load video 95ovIJ3dsNk, broken link
Can not load video kBBmVezBUkg, broken link
Can not load video iFTWM7HV2UI, broken link
12it [00:29,  2.44s/it]Can not load video WfTZ5iIUn4s, broken link
Can not load video t0Cr64zCc38, broken link
14it [00:29,  2.13s/it]Can not load video kyaiTGmwxnU, broken link
Can not load video 9alL95G293s, broken link
16it [00:30,  1.90s/it]Can not load video -nKdufEaL8k, broken link
17it [00:30,  1.82s/it]Can not load video oEIYHTlbeLA, broken link
18it [00:31,  1.73s/it]Can not load video v9EKV2nSU8w, broken link
19it [00:31,  1.65s/it]Can not load video 51k3UASQE5E, broken link
Can not load video VM6HZqQKhok, broken link
Can not load video 51k3UASQE5E, broken link
22it [00:31,  1.44s/it]Can not load video HI7zfpitZpo, broken link
23it [00:31,  1.38s/it]Can not load video FDhlOovaGrI, broken link
24it [00:32,  1.36s/it]Can not load video 08z_xW-szwM, broken link
Can not load video fO2htapfNhA, broken link
26it [00:32,  1.26s/it]Can not load video idfv7Lw4Y_s, broken link
27it [00:32,  1.22s/it]Can not load video I3BJVaioX_k, broken link
28it [00:33,  1.18s/it]Can not load video MB5IX-np5fE, broken link
29it [00:33,  1.15s/it]Can not load video FqrLUtIFVjs, broken link
30it [00:33,  1.12s/it]Can not load video 13zN4-MVM9g, broken link
31it [00:33,  1.08s/it]Can not load video iFTWM7HV2UI, broken link
32it [00:34,  1.07s/it]Can not load video HiwJ0hNl1Fw, broken link
33it [00:34,  1.04s/it]Can not load video 1AT5klu_yAQ, broken link
34it [00:34,  1.02s/it]Can not load video TLZ6W-Nqv1I, broken link
Can not load video iMFJef3xnmg, broken link
36it [00:34,  1.03it/s]Can not load video pxEcvU0Vp_M, broken link
Can not load video kmbui1xF8DE, broken link
38it [00:35,  1.07it/s]Can not load video 2VBkDNzeRZM, broken link
Can not load video yNhu0MG_2MA, broken link
40it [00:36,  1.11it/s]Can not load video VJoQj00RZHg, broken link
41it [00:36,  1.13it/s]Can not load video SF9qq6vQ3Pg, broken link
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/liuxinqi/anaconda3/envs/art-ani/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "load_videos.py", line 72, in run
    save(os.path.join(args.out_folder, partition, path), entry['frames'], args.format)
  File "/home/liuxinqi/disk/study/articulated-animation-main/video-preprocessing/util.py", line 118, in save
    imageio.mimsave(path, frames)
  File "/home/liuxinqi/anaconda3/envs/art-ani/lib/python3.7/site-packages/imageio/core/functions.py", line 347, in mimwrite
    raise RuntimeError('Zero images were written.')
RuntimeError: Zero images were written.
"""

**Comment by AliaksandrSiarohin** [comment]
Most likely your YouTube-dl is old. Try to download it aggain. What do you mean all pretrained models?

**Comment by LiuXinqi12** [comment]
I tried to use the latest version of youtube-di, but it still doesn't work for me. I used all the checkpoints you provided to experiment with the data we collected from real-world scenarios, and found that generalization is limited and the results are not expected. Maybe we need to rebuild the relevant datasets and retrain the network.

**Comment by AliaksandrSiarohin** [comment]
When you run ```./youtube-dl 360bU-vBJOI``` what happens?

**Comment by silverbulletmdc** [comment]
I can download the videos. But there is no `ted384-metadata.csv` in `data`. I found `ted-metadata.csv` file. But all the start and end frame in this file is set to 0. In line 56 of `load_videos.py`,
```
                if (i * ref_fps >= entry['start'] * fps) and (i * ref_fps < entry['end'] * fps):
```
This line will never get True value.
How to fix it? Waiting for your reply.

**Comment by AliaksandrSiarohin** [comment]
I upload the wrong file.
[ted384-metadata.csv](https://github.com/snap-research/articulated-animation/files/6451961/ted384-metadata.csv)

**Comment by silverbulletmdc** [comment]
Thanks!

**Comment by LiuXinqi12** [comment]
Thanks!

**Comment by G-force78** [comment]
> I upload the wrong file. [ted384-metadata.csv](https://github.com/snap-research/articulated-animation/files/6451961/ted384-metadata.csv)

Hi, is this the one needed for ted-youtube model to work?

**Comment by SatyaDewangan05** [comment]
> I upload the wrong file. [ted384-metadata.csv](https://github.com/snap-research/articulated-animation/files/6451961/ted384-metadata.csv)

Very helpful buddy
