### ISSUE TITLE
RuntimeError: imageio.mimread() has read over 256 MiB of image data.

### ISSUE THREAD

**Issue by avani17101** [snap-research/articulated-animation#14]
while running 
```python run.py --config config/ted384.yaml --device_ids 0,1```
I am getting the following error.
![Screenshot from 2021-05-16 17-52-21](https://user-images.githubusercontent.com/33591258/118396949-7d9d0680-b66f-11eb-840e-5f792a49bf3b.png)

A similar error has been pointed here https://github.com/AliaksandrSiarohin/first-order-model/issues/217
I see the memtest is already set to False in the codebase. Not sure why this error.

**Comment by SatyaDewangan05** [comment]
on line 61:
  instead of 
    video = mimread(video)
  use
    video = mimread(video, memtest=False)
