### ISSUE TITLE
TED metadata.csv

### ISSUE THREAD

**Issue by eastchun** [snap-research/articulated-animation#17]
Couldn't find 'ted384-metadata.csv' in './data' folder. 

Instead, there is a file 'ted-metadata.csv ''that has all 0s for 'start' and 'end' entries (but start/end frame numbers are included in video_id).

Is it OK to modify 'load_videos.py' to support this configuration in ted-metadata.csv?

But, I wonder whether ted-metadata.csv is the same as ted384-metadata.csv except start/end frames issue.

**Comment by AliaksandrSiarohin** [comment]
No, See #12.
