### ISSUE TITLE
Colab button link points to FOMM notebook rather than articulated animation

### ISSUE THREAD

**Issue by Norod** [snap-research/articulated-animation#2]
Screenshot:

![Screenshot 2021-04-29 204547](https://user-images.githubusercontent.com/3617152/116595858-70241480-a92c-11eb-94b4-6ea8b341d87c.jpg)

Should point to: https://colab.research.google.com/github/snap-research/articulated-animation/blob/main/demo.ipynb

**Comment by dobrosketchkun** [comment]
Notebook is missing some crucial steps to be usable, could you please add them, @sergeytulyakov ? Like the link to the right github repository, git lfs thingy about checkpoints, etc

**Comment by AliaksandrSiarohin** [comment]
Should be fixed now.

**Comment by dobrosketchkun** [comment]
Indeed, it's all nice now, thank you.

**Comment by Norod** [comment]
👍
