### ISSUE TITLE
Frame rate change

### ISSUE THREAD

**Issue by eastchun** [snap-research/articulated-animation#20]
While the frame rate  (fps) of the original YouTube videos are 29.97 or 25, etc...., 
After running 'load_videos.py', the frame rate of the downloaded/cropped/trimmed videos (for both train and test) are always set to 10 fps. 

Do I need to change this frame rate back to the frame rate of the original video?

**Comment by AliaksandrSiarohin** [comment]
Nope, framerate does not matter there.

**Comment by eastchun** [comment]
because it just trains for two randomly selected frames in order....
