### ISSUE TITLE
Preparing training videos ....

### ISSUE THREAD

**Issue by eastchun** [snap-research/articulated-animation#21]
Would appreciate if you comment on my question below:

Suppose that I trimmed a video (say from  1000th frame to 5000th frame.) for training

In this case, which is is better ?

1) Provide this  trimmed video  as one training video (from 1000th frame to 5000th frame).
2) Divide further (say 1000 ~ 2000, 2000 ~ 3000, 3000 ~ 4000, 4000 ~ 5000) and provide 5 trimmed  training videos.
3) It doesn't matter.

**Comment by sergeytulyakov** [comment]
It's not totally clear to me what you're trying to achieve. If you have just one video of a person and you'd like to generate more videos like that conditioned on some pose, why don't you use Everybody Dance Now or a similar work?

The point of our work is to be able to animate a diverse set of objects in an unsupervised manner, if you're interested in animating a particular object, supervised methods should be preferred.

**Comment by eastchun** [comment]
What I am trying to ask is... 
Suppose that I prepared training videos , say 200 videos trimmed from different YouTube dancing videos, each of them is about 15 sec duration. 

One way is just to use these 200 different training videos (15 sec duration each).
Another way is to further divide each video into (say) 5 sec duration such that I prepare 600 videos (5 sec duration each).

In the latter case, the probability of randomly sampling two training images from the training video pool might be better than former case?
