### ISSUE TITLE
Fail to download TED dataset

### ISSUE THREAD

**Issue by zhangyahu1** [snap-research/articulated-animation#29]
Thanks for sharing your nice work!
I meet a problem when downloading TED dataset. I get:
```
/home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
0it [00:00, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "load_videos.py", line 32, in run
    download(video_id.split('#')[0], args)
  File "load_videos.py", line 25, in download
    video_path], stdout=DEVNULL, stderr=DEVNULL)
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "load_videos.py", line 103, in <module>
    for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
PermissionError: [Errno 13] Permission denied
```
Could you please give me some advice to solve this problem?

**Comment by Thechosenfeng** [comment]
Hi, how did you solve this problem?

**Comment by sinansonlu** [comment]
On Colab, I download youtube-dl into video-preprocessing and set its permissions:
`!wget https://yt-dl.org/downloads/latest/youtube-dl -O youtube-dl
!chmod 755 youtube-dl`

**Comment by notorious-eric** [comment]
Hi, I meet with the problem "OSError: [Errno 8] Exec format error: './youtube-dl'" Do you know what is the issue?

**Comment by wyyfffff** [comment]
> Hi, I meet with the problem "OSError: [Errno 8] Exec format error: './youtube-dl'" Do you know what is the issue?

I meet this issue and I just use `pip install youtube-dl`, and change the args.youtube to youtube-dl. Then I can run it but all the links are broken link.... Do you know how to solve that? I used pip --upgrade to make it latest version

**Comment by notorious-eric** [comment]
> > Hi, I meet with the problem "OSError: [Errno 8] Exec format error: './youtube-dl'" Do you know what is the issue?
> 
> I meet this issue and I just use `pip install youtube-dl`, and change the args.youtube to youtube-dl. Then I can run it but all the links are broken link.... Do you know how to solve that? I used pip --upgrade to make it latest version

You can see #12. Thank you for your suggestion, I have solved it.
