### ISSUE TITLE
basic information about error

### ISSUE THREAD

**Issue by Adorablepet** [snap-research/articulated-animation#4]
Thanks for you sharing code, This is a very great project. But I run, appear error, as follows:
```
Traceback (most recent call last):
  File "demo.py", line 134, in <module>
    main(parser.parse_args())
  File "demo.py", line 113, in main
    checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 59, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/home/zhaopeng/anaconda3/envs/articulatedanimation/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zhaopeng/anaconda3/envs/articulatedanimation/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
my command, as follows:
`CUDA_VISIBLE_DEVICES='0' python demo.py --config config/ted384.yaml --driving_video nv.mp4 --source_image nv.png --checkpoint checkpoints/ted384.pth --mode avd`

my environment, as follows:
```
torch 1.4.0
torchvision 0.5.0
```
thers is a little different from `requirement.txt`, your torchvision is `0.2.1`.

Could you help me, thanks.

**Comment by sergeytulyakov** [comment]
Did you download the models? Please check their size on disk. They should be large, use git lfs (see readme)

**Comment by ftaker887** [comment]
There's a possibility that your python install might have conflicts with packages. You could try using Anaconda to install.

Clone the repository.

`git clone https://github.com/snap-research/articulated-animation.git`

Go the the articulated-animation directory.

`cd articulated-animation`

Create the Anaconda environment.

`conda create -n articulated-animation python=3.7`

Activate the Anaconda environment.

`conda activate articulated-animation`

Now try.

`pip install -r requirements.txt`

Everything should work after that.

**Comment by Adorablepet** [comment]
@sergeytulyakov you are right, I downloaded checkpoints fully, this is okay. I have solved now, thanks.
@ftaker887 Thanks for you.

**Comment by 3herry1in** [comment]
> @sergeytulyakov you are right, I downloaded checkpoints fully, this is okay. I have solved now, thanks. @ftaker887 Thanks for you.
Hi👋 , I'm new to git-lfs and I didn't find the place to download checkpoints, I've been toubled for a very long time. Could you please give me some instructions on downloading them? Thank you very much!!
