### ISSUE TITLE
Retrain on TED dataset

### ISSUE THREAD

**Issue by zhangyahu1** [snap-research/articulated-animation#43]
Thanks for sharing your nice work!

I am trying to retrain your model on TED dataset, and run the command:

> CUDA_VISIBLE_DEVICES=0,1 python run.py --config config/ted384.yaml --device_ids 0,1

With 

> Batch_size = 8, num_epochs: 100,  num_repeats: 150, input: image with png format.

It seems the training process will take more than 7 days. May I know how long did you take? Thanks.

**Comment by zhangyahu1** [comment]
@AliaksandrSiarohin
Is this the same setting reported in the paper? Otherwise it takes too long for training even with 2 GPUs.

**Comment by AliaksandrSiarohin** [comment]
Setting is the same, except the bs. We trained on 8 gpus, around 2-3 days.

**Comment by zhangyahu1** [comment]
Thanks!
