### ISSUE TITLE
source image compatibility with the driving video

### ISSUE THREAD

**Issue by addy1997** [snap-research/articulated-animation#55]
Hi @AliaksandrSiarohin, 

Thanks for sharing this amazing work. While using custom videos with the source images available on the internet, I found a few compatibility-related issues:

1. The generated video is highly distorted if the source image is not appropriately aligned with the driving video.
2. Initial pose of the source image, if not similar to that of the entity in the driving video, fails to process the image and generate a video.]

For instance, the source image only has a face of a person, and in contrast, the driving video has a speaker with movements, the generated video will be full of distortions.

**Comment by AliaksandrSiarohin** [comment]
It works only for the objects of the same kind. Face model for faces, upper body for upper bodies.

**Comment by addy1997** [comment]
> It works only for the objects of the same kind. Face model for faces, upper body for upper bodies.
