### ISSUE TITLE
Question about vox256 model

### ISSUE THREAD

**Issue by ChengBinJin** [snap-research/articulated-animation#7]
@AliaksandrSiarohin 
Hi, I have two simple questions about the vox256 model in your provided checkpoints. 
- What is the resolution of the data for training vox256, 256x256, or 384x384? 
- This model is trained from which version of the VoxCeleb dataset? V1 or V2?

**Comment by AliaksandrSiarohin** [comment]
256, v1

**Comment by ChengBinJin** [comment]
Ok, got it
