### ISSUE TITLE
Git LFS quota limit

### ISSUE THREAD

**Issue by honix** [snap-research/articulated-animation#71]
When I trying to download checkpoints there is a message that repo owner get LFS quota limit. It is possible to share checkpoints on some other file storage, so it can be downloaded?

**Comment by laurentbenaroya** [comment]
According to an older issue, you can get them from here : [https://drive.google.com/drive/folders/1jCeFPqfU_wKNYwof0ONICwsj3xHlr_tb](https://drive.google.com/drive/folders/1jCeFPqfU_wKNYwof0ONICwsj3xHlr_tb)

**Comment by honix** [comment]
Thanks!
